name: Update Git Information
on:
  push:
jobs:
  update-git-information:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Update Git Information
        run: |
          docker run --rm \
            -v "$(pwd)":/app \
            -w /app \
            composer install --no-interaction
          echo "branch,commit_hash,commit_date" > git-information.csv
          git --no-pager log -1 --format="%d" | grep -qE "\((HEAD -> )?(main|master)(, .+)?\)" && \
            echo "$(git rev-parse --abbrev-ref HEAD),$(git rev-parse HEAD),$(git log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M:%S')" >> git-information.csv
          chmod 644 git-information.csv
      - name: Commit Git Information
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add git-information.csv
          git commit --author "GitHub Action <action@github.com>" -m "Update Git Information"
          git push --force-with-lease