name: update-git-information

on:
  push:
    branches:
      - master

jobs:
  update-git-information:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Update Git Information
        run: |
          docker run --rm \
            -v "$(pwd)":/app \
            -w /app \
            composer install --no-interaction
          echo "branch,commit_hash,commit_date" > git-information.csv
          branch_name=$(echo ${GITHUB_REF#refs/heads/})
          echo "$branch_name,$(git rev-parse HEAD),$(git log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M:%S')" >> git-information.csv
          chmod 644 git-information.csv
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add git-information.csv
          git commit --author "GitHub Action <action@github.com>" -m "chore(Github-Autocommit-Action): update git-information.csv with latest information"
          git push --force-with-lease